baseURL = "/"
languageCode = "fa-ir"
title = "آزادافزار"
theme = "mainroad"
paginate = "10" # Number of posts per page

[Author]
    name = "سید مهدی نقوی"

[Params]
    description = "درباره نرم‌افزار‌های آزاد"
    mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
    


