baseURL = "/"
languageCode = "fa-ir"
title = "آزادافزار-همه چیز درباره نرم‌افزار‌های آزاد"
theme = "mainroad"
paginate = "10" # Number of posts per page

[Author]
    name = "سید مهدی نقوی"

[Params]
    description = "لینوکس، نرم‌افزار‌های آزاد. معرفی، آموزش، اخبار"
    authorbox = true
    post_meta = ["author", "date", "categories"] # Order of post meta information
    googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700"
    pager = "true"
    
[Params.logo]
    title = "آزادافزار"

[Params.style.vars]
    # highlightColor = "#e22d30" # Override highlight color
    highlightColor = "#0981c6"
    
[Params.sidebar]
    home = "right"
    widgets = ["recent", "categories", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget


