baseURL = "/"
languageCode = "fa-ir"
title = "آزادافزار"
theme = "mainroad"
paginate = "10" # Number of posts per page

[Author]
    name = "سید مهدی نقوی"

[Params]
    description = "درباره نرم‌افزار‌های آزاد"
    authorbox = true
    post_meta = ["author", "date", "categories"] # Order of post meta information
[Params.style.vars]
    #highlightColor = "#e22d30" # Override highlight color
    highlightColor = "blue"
    
      


